apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: components
  namespace: flux-system
spec:
  interval: 1m
  retryInterval: 1m
  timeout: 1m
  path: "./components"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
