apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mysql-operator
  namespace: mysql-system
spec:
  interval: 30m
  chart:
    spec:
      chart: pxc-operator
      version: "1.18.0"
      sourceRef:
        kind: HelmRepository
        name: percona
        namespace: mysql-system
      interval: 12h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    replicaCount: 1

    watchAllNamespaces: true

    rbac:
      create: true

    serviceAccount:
      create: true

    resources:
      limits:
        cpu: 200m
        memory: 250Mi
      requests:
        cpu: 100m
        memory: 100Mi

    disableTelemetry: true

    logLevel: "INFO"
    logStructured: true
